[package]
name = "home-intercom-server-rs"
version = "0.1.0"
authors = ["Kory <korygm33@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
futures-util = "0.3.15"
